### ISSUE TITLE
README would be nice

### ISSUE THREAD

**Issue by TamaMcGlinn** [paradust7/webshims#1]
Hi paradust,

I'm trying to get this repo running to improve the network performance in minetest-wasm, as I suspect the single proxy server is a bottleneck. I assumed, since there is a cmake file, that I was supposed to do cmake . and make on a linux machine, but your use of stropts.h makes that impossible. Are we supposed to compile this through emscripten?

It would be great to have a basic readme stating how to compile & run the project, and of course mention that it's to replace the proxy server in [minetest-wasm's static/launcher.js line 576](https://github.com/paradust7/minetest-wasm/blob/main/static/launcher.js#L576), as pointed out by [this relevant issue](https://github.com/paradust7/minetest-wasm/issues/20).

**Comment by TamaMcGlinn** [comment]
If you would be interested in doing paid work on minetest-wasm, please reach out on [tama@mcglinn-software.com](mailto:tama@mcglinn-software.com).

**Comment by paradust7** [comment]
This is a library and not a standalone project. It can only be built with emscripten. The build script is here:

https://github.com/paradust7/minetest-wasm/blob/main/build_webshims.sh#L10

There are proxy servers for each region, make sure you are using the correct region:

North America (Dallas) - wss://na1.dustlabs.io/mtproxy
South America (Sao Paulo) - wss://sa1.dustlabs.io/mtproxy
Europe (Frankfurt) - wss://eu1.dustlabs.io/mtproxy
Asia (Singapore) - wss://ap1.dustlabs.io/mtproxy
Australia (Melbourne) - wss://ap2.dustlabs.io/mtproxy

The default is minetest.dustlabs.io which is in California.

I will follow-up on that issue, since many people have been asking about it.

**Comment by paradust7** [comment]
@TamaMcGlinn Regarding network performance

Web apps are limited to web networking protocols, such as WebSockets or WebRTC. A proxy is required because minetest servers only talk UDP. WebRTC allows data channels which are UDP-like, but it is considerably more difficult to use, which is why I'm only using WebSockets for now. (which are TCP-based, so more bottlenecked)

I am hoping to switch to WebRTC at some point in the future, but I have higher priorities, so it may not happen for a long time. With some additional work, Minetest servers could natively support both UDP and WebRTC, so that proxying is no longer necessary.

For legal reasons, I am not able to do any paid work, but if you'd like to donate I setup a liberapay (https://liberapay.com/paradust).

If you have questions about the proxy, please follow-up on the other issue. Thanks.
